# Generated by Django 4.1.4 on 2023-01-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishingchannel',
            old_name='image_url',
            new_name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='publishingchannel',
            name='youtube_channel_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
