# Generated by Django 4.1.4 on 2023-01-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0002_rename_image_url_publishingchannel_thumbnail_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishingchannel',
            old_name='youtube_channel_id',
            new_name='channel_id',
        ),
    ]
