# Generated by Django 4.1.4 on 2023-01-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0004_episode_duration_episode_episode_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='viewcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishingchannel',
            name='channel_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publishingchannel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishingchannel',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
