# Generated by Django 4.1.4 on 2023-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0005_alter_episode_description_alter_episode_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio')], default='video', max_length=200),
            preserve_default=False,
        ),
    ]
