# Generated by Django 4.1.4 on 2023-01-31 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abokistde', '0006_episode_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='user',
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
