# Generated by Django 4.1.5 on 2023-02-05 07:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abokistde', '0007_remove_userlogin_user_alter_usersubscriptions_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscriptions',
            new_name='UserSubscription',
        ),
    ]
