# Generated by Django 4.1.5 on 2023-02-09 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0008_rename_usersubscriptions_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('icon_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='publishingchannel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abokistde.provider'),
        ),
    ]
