# Generated by Django 4.1.5 on 2023-02-09 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0009_provider_alter_publishingchannel_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishingchannel',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abokistde.provider'),
        ),
    ]
