# Generated by Django 4.1.5 on 2023-02-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0010_alter_publishingchannel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='extractor',
            field=models.CharField(default='youtube', max_length=200),
            preserve_default=False,
        ),
    ]
