# Generated by Django 4.1.5 on 2023-02-09 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0011_provider_extractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='technical_name',
        ),
    ]
