# Generated by Django 4.1.5 on 2023-02-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0013_rename_display_name_provider_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='extractor',
        ),
    ]
