# Generated by Django 4.1.5 on 2023-02-09 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0014_remove_provider_extractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='extractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abokistde.extractor'),
        ),
    ]
