# Generated by Django 4.1.5 on 2023-02-09 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abokistde', '0015_extractor_provider_extractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='extractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abokistde.extractor'),
            preserve_default=False,
        ),
    ]
