# Generated by Django 3.2.23 on 2024-01-27 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abokistde', '0018_watchlaterepisode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchLaterEpisode',
            new_name='FavoriteEpisode',
        ),
    ]
